vich_uploader:
    db_driver: orm

    mappings:
        jeux_images:
            uri_prefix: /uploads/jeux
            upload_destination: '%kernel.project_dir%/public/uploads/jeux'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        profile_pictures:
                    uri_prefix: /uploads/profile_pictures
                    upload_destination: '%kernel.project_dir%/public/uploads/profile_pictures'
                    delete_on_remove: true
                    delete_on_update: true